### ISSUE TITLE
Have you reproduced the results in the paper?

### ISSUE THREAD

**Issue by rumusan** [knjcode/filter-response-normalization-layer-pytorch#4]
hi, have you reproduced the results in the paper? thank you.

**Comment by knjcode** [comment]
@rumusan Thank you for the question.
I haven't yet tried to reproduce the results with the settings according to the paper.

However, I did experiments with small dataset (like Tiny-Imagenet).
And accuracy was lower when using FRN layer.


## The details of the experiment

|model|top1 val acc (best epoch)|
|:----------|:------------------|
|PreAct ResNet50 (BN + ReLU)  |81.47 (99epoch)    |
|PreAct ResNet50 (FRN + TLU)  |79.68 (102epoch)   |

### Dataset

ImageNet reduced to 200 classes (same as Tiny-Imagenet class).
However, use the image size of the original ImageNet dataset, not the Tiny-Imagenet 64x64 image size.

### Settings

batch_size=256 (32 per GPU)  Use small batch size for FRN layer 
Initial_lr=0.1, weight_decay=1e-5
epochs=120 (linear warmup 10epoch + cosine annealing 110epoch)

RandomResizedCrop(scale:0.08,1.0, ratio:0.75,1.33)
HorizontalFlip(p=0.5), RandomRotation(degree=3)
ColorJitter(brightness,contrast,saturation=0.10, hue=0.05)
PCA Noise(p=0.1)

**Comment by rumusan** [comment]
Thanks for your reply !
